HEIGHT = 700
WIDTH = 1280
ACC = 0.5
FRIC = -0.12
FPS = 60
START_MENU = 'start_menu'
GAME = 'game'
LEVEL = 'level'
GRAVITY = 0.8
LEVEL_SELECT = "level_select"
CARD_SIZE = 240
EFFECT_SOUND = "../assets/raw/event_effects/"
BGM_PATH = "../assets/raw/background_music/"
FONT_PATH = "assets/font/LilitaOne-Regular.ttf"
SELECTABLE_PLAYER_POS_X = WIDTH * 6/8 + 50
SELECTABLE_PLAYER_POS_Y = HEIGHT / 3
